project:
  type: website
  output-dir: docs
editor_options:
  chunk_output_type: console
knitr:
  opts_chunk:
    collapse: true
    comment: "#>"

website:
  title: "J M Barbone"
  navbar:
    right:
      - icon: person-circle
        href: about.html
      - icon: github
        href: https://github.com/jmbarbone
      - icon: mastodon
        href: https://fosstodon.org/@barbone
      - icon: linkedin
        href: https://linkedin.com/in/jmbarbone
      - icon: folder
        href: https://www.researchgate.net/profile/Jordan-Barbone-2
      - icon: google
        href: https://scholar.google.com/citations?user=R6GyUVYAAAAJ&hl=en&oi=ao
      - icon: flower3
        href: anthology.html
      - icon: file-text
        href: https://github.com/jmbarbone/barbone-cv/blob/master/Barbone-CV.pdf
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    code-copy: true
    code-fold: show
    code-tools: true
footnotes-hover: true
reference-location: margin
highlight-style: github
execute: 
  freeze: auto