project:
  type: website

website:
  title: "quarto-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jmbarbone
      - icon: twitter
        href: https://twitter.com/jmbarbone
      - icon: linkedin
        href: https://linkedin.com/in/jmbarbone
      - icon: folder
        href: https://www.researchgate.net/profile/Jordan-Barbone-2
      - icon: google
        href: https://scholar.google.com/citations?user=R6GyUVYAAAAJ&hl=en&oi=ao
format:
  html:
    theme: solar
    css: styles.css



