project:
  type: website
  output-dir: docs
  knitr:
    opts_chunk:
      collapse: true
      comment: "#>"

website:
  title: "J M Barbone"
  navbar:
    right:
      - icon: person-circle
        href: about.html
      - icon: github
        href: https://github.com/jmbarbone
      - icon: twitter
        href: https://twitter.com/jmbarbone
      - icon: linkedin
        href: https://linkedin.com/in/jmbarbone
      - icon: folder
        href: https://www.researchgate.net/profile/Jordan-Barbone-2
      - icon: google
        href: https://scholar.google.com/citations?user=R6GyUVYAAAAJ&hl=en&oi=ao
format:
  html:
    theme: flatly
    css: styles.css

