---
title: "About"
about:
  template: marquee
  links:
    - icon: mastodon
      text: Fosstodon
      href: https://fosstodon.org/@barbone
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com/in/jmbarbone
    - icon: github
      text: Github
      href: https://github.com/jmbarbone
---

```{r}
#| echo: false
#| column: screen-inset-shaded
#| message: false
#| fig-width: 12
#| fig-height: 8
#| fig-align: center

now_ym <- function() {
  now <- Sys.Date()
  year <- as.double(format(now, "%Y"))
  month <- as.double(format(now, "%m"))
  year + round(month / 12, 2)
}

now_year1 <- function() {
  as.double(format(Sys.Date(), "%Y")) + 1.0
}

VisualResume::VisualResume(
  titles.left      = c("Jordan Mark Barbone, M.A.", "R Developer", "Scientist, Data"),
  titles.left.cex  = c(3, 2, 2),
  titles.right     = c("", ""),
  titles.right.cex = c(1, 1),
  timeline.labels  = c("Education/Academic",
                       "Work/Professional"),
  timeline = as.data.frame(tibble::tribble(
    ~title,                     ~sub,                       ~side, ~start,  ~end,
    "WCU",                      "UG Psych Student",         1,     2011.75, 2015.50,
    "LARC",                     "Writing Tutor",            1,     2014.75, 2015.50,
    "Bracket",                  "Clinical Assistant",       0,     2015.75, 2016.50,
    "Bracket",                  "Clinical Associate",       0,     2016.50, 2018.00,
    "WCU",                      "Non-degree Grad Student",  1,     2016.75, 2017.75,
    "WCU",                      "Grad Psych Student",       1,     2017.75, 2019.50,
    "Bracket",                  "Clinical Data Specialist", 0,     2018.00, 2019.00,
    "Signant Health",           "Clinical Data Scientist",  0,     2019.00, 2019.92,
    "Madrigal Pharmaceuticals", "Principal Data Analyst",   0,     2019.92, 2021.50,
    "Cogstate Ltd",             "Data Scientist",           0,     2021.50, now_year1()
  )),
  timeline.cex = c(1.1, 0.95),
  milestones = tibble::tribble(
    ~title,            ~sub,                        ~year,
    "Bachelor of Art", "Psychology, minor Biology", 2015.50,
    "Master of Art",   "General Psychology",        2019.50,
  ),
  events = as.data.frame(tibble::tribble(
    ~year,   ~title,
    2016.50, "Adopted Buckley, the best black lab",
    2017.33, paste("Irani, Barbone, Beausoleil, & Gerald (2017)",
                   "Is asthma associated with impaired cognition?",
                   sep = "\n"),
    # 2018.50, "Made this website",
    2019.00, "Charter Member of Data Science Team",
    2019.25, paste("Solomon, Barbone, et al. (2019)",
                   "Comparing the standard and electronic versions of the ADAS-cog ",
                   sep = "\n"),
    2021.50, "First R package on CRAN: {mark}",
    2021.58, paste("Younossi, et al. (2021)",
                   "Hepatic fat reduction ... in patients with NASH ... improvement of QoL",
                   sep = "\n")
  )),
  events.cex = 1.25,
  interests = list(
    "Psychology" = c(rep("Cog", 2),
                     rep("Neuropsych", 1),
                     rep("Quant", 3),
                     rep("Clinical", 1)),
    "R"          = c(rep("Stat program", 2),
                     rep("Data manip", 2),
                     rep("Pkg dev", 2),
                     rep("Data Vis", 2)),
    "Other"      = c(rep("Buckley (dog)", 3),
                     rep("Bowie", 3),
                     rep("Coffee", 3))),
  year.steps = 1
)
```

Visual above made with [Nathaniel Phillip's VisualResume](https://github.com/ndphillips/VisualResume).

I am currently working as a Data Scientist at [Cogstate](https://cogstate.com) where I get to work with our Science and Data teams work with outcomes from computerized, cognitive assessments and other outcomes data (e.g., COA, ClinRO, PRO).

I started learning R in my gradate statistics classes to avoid the future pains of having to use or only being familiar with SPSS.
Learning R then launched me into a bigger role at Bracket (now [Signant Health](https://signanthealth.com/)) where I had the pleasure to work with our Clinical Science team to understand and interpret their data.
This gave us the opportunity to learn more about our technologies, approaches, and quality of reporting in the clinical trials we were assisting.
Here I was a charter member of the Data Science team and have the pleasure of enhancing our trial monitoring products, training other Data Science programmers, and contributing to automation and reporting efforts of our Clinical Data Management team.
I worked as the Principal Data Analyst for [Madrigal Pharmaceuticals](https://madrigalpharma.com/), helping our Research & Development team monitor our current trials and prepare summary reports.
This was a bit of a departure for me to work with more lab and imaging data and in an area I didn't have any experience: liver disease.
Despite that, there were plenty of data I recognized: from clinical operations, data management, and even some interested PRO QoL data.

I have a Masters of Art in Psychology and have spent my graduate and undergrad classes engaging in Neuropsychology and Cognitive topics.
Some of these topics have included understanding how music affects our ability on tests of aptitude.
This, of course, was the basis of my Masters Thesis and hours of reading journal article after journal article.
Of course I've also been very interested in immersing myself more into statistics, statistical programming, and special psychometric subjects.
Please browse the [Anthology page](https://jmbarbone.github.io/homepage/anthology) where I have tried to compile projects, papers, and presentations I've written in and out of class.

And of course, here is my dog's IG [TheLabBuckley](https://www.instagram.com/thelabbuckley/).
It's mostly him sleeping.
